In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2

In [3]:
# importing the module
import cv2
  
coordinates_x=[]
coordinates_y = []
# function to display the coordinates of
# of the points clicked on the image
def click_event(event, x, y, flags, params):
 
    # checking for left mouse clicks
    if event == cv2.EVENT_LBUTTONDOWN:
 
        # displaying the coordinates
        # on the Shell
        print(x, ' ', y)
 
        # displaying the coordinates
        # on the image window
        coordinates_x.append(x)
        coordinates_y.append(y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(img, str(x) + ',' +
                    str(y), (x,y), font,
                    1, (255, 0, 0), 2)
        cv2.imshow('image', img)
 
    # checking for right mouse clicks    
    if event==cv2.EVENT_RBUTTONDOWN:
 
        # displaying the coordinates
        # on the Shell
        print(x, ' ', y)
 
        # displaying the coordinates
        # on the image window
        font = cv2.FONT_HERSHEY_SIMPLEX
        b = img[y, x, 0]
        g = img[y, x, 1]
        r = img[y, x, 2]
        cv2.putText(img, str(b) + ',' +
                    str(g) + ',' + str(r),
                    (x,y), font, 1,
                    (255, 255, 0), 2)
        cv2.imshow('image', img)
 
# driver function
if __name__=="__main__":
 
    # reading the image
    img = cv2.imread('Brain (2).jpg', 1)
 
    # displaying the image
    cv2.imshow('image', img)
 
    # setting mouse handler for the image
    # and calling the click_event() function
    cv2.setMouseCallback('image', click_event)
 
    # wait for a key to be pressed to exit
    k = cv2.waitKey(0) & 0xFF

    if k == 27:  # close on ESC key
        cv2.destroyAllWindows()

In [30]:
coordinates = pd.read_csv("coordinates.csv")
coordinates.head()
coordinates = coordinates.iloc[:,1:]
coordinates.head()

     X    Y
0  335   46
1  429   45
2  288  104
3  451  104
4  289  205

In [31]:
coordinates_x = coordinates.iloc[:,0]
coordinates_y = coordinates.iloc[:,1]

In [32]:
len(coordinates_x)

19

In [33]:
coordinates = {"X":coordinates_x,"Y":coordinates_y}
coordinates = pd.DataFrame(coordinates)
coordinates.head()

     X    Y
0  335   46
1  429   45
2  288  104
3  451  104
4  289  205

In [8]:
coordinates.to_csv("Coordinates.csv")

In [14]:
# path

   
# Reading an image in default mode
image = cv2.imread('Brain (1).jpg', 1)
   
# Window name in which image is displayed
window_name = 'Image'
  
# Center coordinates
center_coordinates = (coordinates_x[1],coordinates_y[1] )
 
# Radius of circle
radius = 14
  
# Blue color in BGR   
color = (255, 0, 0)
  
# Line thickness of 2 px
thickness = -1
  
# Using cv2.circle() method
# Draw a circle with blue line borders of thickness of 2 px



TEXT_FACE = cv2.FONT_HERSHEY_DUPLEX
TEXT_SCALE = 0.4
TEXT_THICKNESS = 1
TEXT = "Fp1"
#image = cv2.flip(image, 1)
image = cv2.circle(image, center_coordinates, radius, color, thickness)
text_size, _ = cv2.getTextSize(TEXT, TEXT_FACE, TEXT_SCALE, TEXT_THICKNESS)
text_origin = (coordinates_x[1] - int(text_size[0] / 2), coordinates_y[1] + int(text_size[1] / 2))

cv2.putText(image, TEXT, text_origin, TEXT_FACE, TEXT_SCALE, (255,255,255), TEXT_THICKNESS, cv2.LINE_AA)

cv2.imshow(window_name, image)
k = cv2.waitKey(0) & 0xFF
# Displaying the image
if k == 27:
    # close on ESC key
    cv2.destroyAllWindows()

In [84]:
import pandas as pd
data = pd.read_csv("/Users/sultm0a/Downloads/Spectral_decomposed_GC_1.csv")

In [85]:
data.head()

  Unnamed: 0  T3_Delta  T3_Theta  T3_Alpha  T3_Beta  T3_Gamma
0  Fp1_Delta         1         0         0        0         0
1  Fp2_Delta         0         0         0        0         0
2   F3_Delta         0         0         0        0         0
3   F4_Delta         0         0         0        0         0
4   C3_Delta         1         0         0        0         0

In [86]:
index = data.iloc[:,0]
index

0     Fp1_Delta
1     Fp2_Delta
2      F3_Delta
3      F4_Delta
4      C3_Delta
        ...
90     T5_Gamma
91     T6_Gamma
92     Fz_Gamma
93     Cz_Gamma
94     Pz_Gamma
Name: Unnamed: 0, Length: 95, dtype: object

In [87]:
data = data.iloc[:,1:6]
data.index = index
len(data.index)

95

In [88]:
95/5

19.0

In [89]:
data.iloc[19,:]

T3_Delta    0
T3_Theta    1
T3_Alpha    0
T3_Beta     0
T3_Gamma    0
Name: Fp1_Theta, dtype: int64

In [90]:
data.head()

            T3_Delta  T3_Theta  T3_Alpha  T3_Beta  T3_Gamma
Unnamed: 0
Fp1_Delta          1         0         0        0         0
Fp2_Delta          0         0         0        0         0
F3_Delta           0         0         0        0         0
F4_Delta           0         0         0        0         0
C3_Delta           1         0         0        0         0

In [91]:
data.iloc[19:2*19,0]

Unnamed: 0
Fp1_Theta    0
Fp2_Theta    0
F3_Theta     0
F4_Theta     0
C3_Theta     1
C4_Theta     0
P3_Theta     0
P4_Theta     0
O1_Theta     0
O2_Theta     0
F7_Theta     0
F8_Theta     1
T3_Theta     2
T4_Theta     1
T5_Theta     0
T6_Theta     0
Fz_Theta     0
Cz_Theta     0
Pz_Theta     0
Name: T3_Delta, dtype: int64

In [92]:
# Bands delta, theta,alpha,beta,gamma
channels = ['Fp1','Fp2','F3','F4','C3','C4','P3','P4','O1','O2','F7','F8','T3','T4','T5','T6','Fz','Cz','Pz']
for i in range(0,5): # this one is for bands 
    
    image = cv2.imread('Brain (2).jpg', 1) # Reading the Image
    bands = ['delta','theta','alpha','beta','gamma']
    for j in range(0,5):
        # This one is for going through each of the 19 channels for one frequency
        
        data_freq = data.iloc[j*19:(j+1)*19,i]
        name = 'T3-'+str(bands[i])+'-'+str(bands[j])
        
        for k in range(0,len(data_freq)):
            if data_freq.iloc[k] >=1:
                center_coordinates = (coordinates_x[k],coordinates_y[k] ) 
                color = (0,0,255)
                image = cv2.circle(image, center_coordinates, radius, color, thickness)
                TEXT_FACE = cv2.FONT_HERSHEY_DUPLEX
                TEXT_SCALE = 0.4
                TEXT_THICKNESS = 1
                TEXT = str(channels[k])
                text_size, _ = cv2.getTextSize(TEXT, TEXT_FACE, TEXT_SCALE, TEXT_THICKNESS)
                text_origin = (coordinates_x[k] - int(text_size[0] / 2), coordinates_y[k] + int(text_size[1] / 2))

                cv2.putText(image, TEXT, text_origin, TEXT_FACE, TEXT_SCALE, (255,255,255), TEXT_THICKNESS, cv2.LINE_AA)
            if k == 12:
                center_coordinates = (coordinates_x[k],coordinates_y[k] ) 
                color = (238,130,238)
                image = cv2.circle(image, center_coordinates, radius, color, thickness)
                TEXT_FACE = cv2.FONT_HERSHEY_DUPLEX
                TEXT_SCALE = 0.4
                TEXT_THICKNESS = 1
                TEXT = str(channels[k])
                text_size, _ = cv2.getTextSize(TEXT, TEXT_FACE, TEXT_SCALE, TEXT_THICKNESS)
                text_origin = (coordinates_x[k] - int(text_size[0] / 2), coordinates_y[k] + int(text_size[1] / 2))
                cv2.putText(image, TEXT, text_origin, TEXT_FACE, TEXT_SCALE, (255,255,255), TEXT_THICKNESS, cv2.LINE_AA)
                
            if data_freq.iloc[k] <1:
                center_coordinates = (coordinates_x[k],coordinates_y[k] ) 
                color = (255,0,0)
                image = cv2.circle(image, center_coordinates, radius, color, thickness)
                TEXT_FACE = cv2.FONT_HERSHEY_DUPLEX
                TEXT_SCALE = 0.4
                TEXT_THICKNESS = 1
                TEXT = str(channels[k])
                text_size, _ = cv2.getTextSize(TEXT, TEXT_FACE, TEXT_SCALE, TEXT_THICKNESS)
                text_origin = (coordinates_x[k] - int(text_size[0] / 2), coordinates_y[k] + int(text_size[1] / 2))

                cv2.putText(image, TEXT, text_origin, TEXT_FACE, TEXT_SCALE, (255,255,255), TEXT_THICKNESS, cv2.LINE_AA)
     
                
        name = name +".png"
        path = '/Users/sultm0a/Downloads/'+name
        print(name)
        cv2.imwrite(name, image)

T3-delta-delta.png
T3-delta-theta.png
T3-delta-alpha.png
T3-delta-beta.png
T3-delta-gamma.png
T3-theta-delta.png
T3-theta-theta.png
T3-theta-alpha.png
T3-theta-beta.png
T3-theta-gamma.png
T3-alpha-delta.png
T3-alpha-theta.png
T3-alpha-alpha.png
T3-alpha-beta.png
T3-alpha-gamma.png
T3-beta-delta.png
T3-beta-theta.png
T3-beta-alpha.png
T3-beta-beta.png
T3-beta-gamma.png
T3-gamma-delta.png
T3-gamma-theta.png
T3-gamma-alpha.png
T3-gamma-beta.png
T3-gamma-gamma.png

In [47]:
for i in data.iloc[:,3]:
    print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
1
0
1
0
1
0
1
0
2
1
2
1
1
1
0
2
2
1
2
2
2
2
2
2
1
2
2
3
1
2
1
2
3
1
2
1
2
2
2
1
1
2
2
2
2
1
3
1
1
1
2
2
2